# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qr.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QRGENERATOR(object):
    def setupUi(self, QRGENERATOR):
        QRGENERATOR.setObjectName("QRGENERATOR")
        QRGENERATOR.resize(400, 274)
        self.textEdit = QtWidgets.QTextEdit(QRGENERATOR)
        self.textEdit.setGeometry(QtCore.QRect(80, 30, 301, 41))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(QRGENERATOR)
        self.textEdit_2.setGeometry(QtCore.QRect(80, 100, 301, 41))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton = QtWidgets.QPushButton(QRGENERATOR)
        self.pushButton.setGeometry(QtCore.QRect(160, 200, 94, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(QRGENERATOR)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 200, 94, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(QRGENERATOR)
        self.label.setGeometry(QtCore.QRect(20, 40, 51, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(QRGENERATOR)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 51, 21))
        self.label_2.setObjectName("label_2")
        self.pushButton_3 = QtWidgets.QPushButton(QRGENERATOR)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 190, 41, 41))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(QRGENERATOR)
        QtCore.QMetaObject.connectSlotsByName(QRGENERATOR)

    def retranslateUi(self, QRGENERATOR):
        _translate = QtCore.QCoreApplication.translate
        QRGENERATOR.setWindowTitle(_translate("QRGENERATOR", "Dialog"))
        self.pushButton.setText(_translate("QRGENERATOR", "cancel"))
        self.pushButton_2.setText(_translate("QRGENERATOR", "Generate"))
        self.label.setText(_translate("QRGENERATOR", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">URL</span></p></body></html>"))
        self.label_2.setText(_translate("QRGENERATOR", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">FILE</span></p></body></html>"))
        self.pushButton_3.setText(_translate("QRGENERATOR", "info"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QRGENERATOR = QtWidgets.QDialog()
    ui = Ui_QRGENERATOR()
    ui.setupUi(QRGENERATOR)
    QRGENERATOR.show()
    sys.exit(app.exec_())
